version: '3.9'

services:
  app1:
    build:
      context: ./app1
    container_name: app1
    ports:
      - "8084:7860"  # ✅ Gradio runs on port 7860
    restart: always

  app2:
    build:
      context: ./app2
    container_name: app2
    expose:
      - "8000"

  nginx2:
    image: nginx:alpine
    container_name: nginx2
    ports:
      - "8085:80"
    volumes:
      - ./app2/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app2

  app3:
    build:
      context: ./app3
    container_name: app3
    expose:
      - "8000"

  nginx3:
    image: nginx:alpine
    container_name: nginx3
    ports:
      - "8086:80"
    volumes:
      - ./app3/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app3
