version: '3.8'

services:
  app1:
    build: ./app1
    ports:
      - "8001:80"
    container_name: fastapi-app1

  app2:
    build: ./app2
    ports:
      - "8002:80"
    container_name: fastapi-app2

  app3:
    build: ./app3
    ports:
      - "8003:80"
    container_name: fastapi-app3
